### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/ggr#10]
* [x] Log request ID
* [x] Log session creation time (in seconds) in CREATED log entry
* [x] Unsupported browser log entry should be: ```[{}] [UNSUPPORTED_BROWSER] [{}] [{}] [{}]", requestId, user, remoteHost, browser```. User can be for simplicity = unknown.
* [x] Session attempt log entry: ```[{}] [SESSION_ATTEMPTED] [{}] [{}] [{}] [{}] [{}]", requestId, user, remoteHost, browser, route, attemptNumber```.
* [x] Session created entry: ```[{}] [{}] [SESSION_CREATED] [{}] [{}] [{}] [{}] [{}] [{}]", requestId, createdDurationSeconds, user, remoteHost, browser, route, sessionId, attemptNumber```
* [x] Session failed entry: ```[{}] [SESSION_FAILED] [{}] [{}] [{}] [{}] - {}", requestId, user, remoteHost, browser, route, errorMessage```
* [x] Session not created (all hosts failed) entry: ```[{}] [SESSION_NOT_CREATED] [{}] [{}] [{}]", requestId, user, remoteHost, browser```. This is not logged right now!
* [x] Session deleted: ```[SESSION_DELETED] [{}] [{}] [{}]", remoteHost, route, sessionId```
* [x] Bad JSON format: ```[BAD_JSON] [{}] [{}]", remoteHost, json```
* [x] Browser not set: ```[BROWSER_NOT_SET] [{}] [{}]", remoteHost, json```

**Comment by aandryashin** [comment]
Implemented, see tests output.

**Comment by vania-pooh** [comment]
@aandryashin btw, we don't need to log remote host port:
```
2016/06/26 15:33:17 [9] [SESSION_FAILED] [unknown] [127.0.0.1:47312] [browser-1.0] [127.0.0.1:50375]
```
should be
```
2016/06/26 15:33:17 [9] [SESSION_FAILED] [unknown] [127.0.0.1] [browser-1.0] [127.0.0.1:50375]
```

**Comment by aandryashin** [comment]
Done.
