### ISSUE TITLE
Version processing issues

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/ggr#27]
* [ ] **Default version processing.** When version = "" we always get "Unsupported browser error". Default version should be used instead.
* [ ] **Partial version matching**. We match version by "HasPrefix" predicate. E.g. when version = 46 and real version = 46.0 we still send to hubs initial version but should replace version in request by **46.0**.

**Comment by vania-pooh** [comment]
Decided to match version by equals only or default version.

**Comment by aandryashin** [comment]
Fixed in 5f29d4911089594b7e1098854a9d78f1721d3a16.
