### ISSUE TITLE
Add doc.go and upload to https://godoc.org

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/ggr#39]
Need to add doc.go file with short description and verify it's being shown on godoc.org. This is mandatory to be published to awesome-go.

**Comment by aandryashin** [comment]
https://godoc.org/github.com/aandryashin/selenoid

**Comment by aandryashin** [comment]
https://godoc.org/github.com/aandryashin/ggr

**Comment by aandryashin** [comment]
Docs generated from package comments. We need to add them.

**Comment by vania-pooh** [comment]
I know but I'm speaking about these two:
https://github.com/gorilla/mux/blob/master/doc.go
https://godoc.org/github.com/gorilla/mux
