### ISSUE TITLE
Can not initialize new session

### ISSUE THREAD

**Issue by idanci** [aandryashin/ggr#42]
```bash
browser = Watir::Browser.new(:remote, url: "http://ivand:password@127.0.0.1:4444/wd/hub", desired_capabilities: Selenium::WebDriver::Remote::Capabilities.send(:firefox, {}))
```
```bash
-> POST session
   >>> http://ivand:password@127.0.0.1:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"firefox","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false}}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"193"}
<- unsupported browser: firefox
Exception `Selenium::WebDriver::Error::WebDriverError' at /Users/ivan/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:85 - unexpected response, code=404, content-type="text/plain"
unsupported browser: firefox
```

docker logs:
```bash
2017/03/09 16:01:15 Users file is [/etc/grid-router/users.htpasswd]
2017/03/09 16:01:15 Loading configuration files from [/etc/grid-router/quota]
2017/03/09 16:01:15 Loaded configuration from [/etc/grid-router/quota/test.xml]:
<browsers xmlns="urn:config.gridrouter.qatools.ru">
  <browser name="firefox" defaultVersion="52">
    <version number="52">
      <region name="1">
        <host name="localhost" port="4445" count="15"></host>
      </region>
    </version>
  </browser>
</browsers>
2017/03/09 16:01:15 Listening on init activated [::]:4444
2017/03/09 16:01:30 [0] [UNSUPPORTED_BROWSER] [ivand] [10.0.2.2] [firefox]
2017/03/09 16:02:05 [14] [UNSUPPORTED_BROWSER] [ivand] [10.0.2.2] [firefox]
```
"ff", "marionette", "chrome", all the browser names give the same unsupported browser error

When opening `http://ivand:password@localhost:4444/wd/hub` in browser it shows `404 page not found`

In the same time no problems when addressing hub directly:
```ruby
browser = Watir::Browser.new(:remote, url: "http://127.0.0.1:4445/wd/hub", desired_capabilities: Selenium::WebDriver::Remote::Capabilities.send(:firefox, {}))
```

Followed instructions from https://godoc.org/github.com/aandryashin/ggr

**Comment by vania-pooh** [comment]
Your quota file name should exactly match your user name. I.e. for use ```ivand``` you should have ```ivand.xml```. According to log files your have ```test.xml```. So just rename test.xml to ```ivand.xml``` and hot reload quota information like that (or just restart container):
```
# docker kill -s HUP <container-name>
```

**Comment by idanci** [comment]
@vania-pooh many thanks, indeed, I can use the quota now, however still can not acquire a session.

```bash
ivand@debian:~$ firefox -v
Mozilla Firefox 52.0
```

```bash
=> browser = Watir::Browser.new(:remote, url: "http://ivand:34erdfcv@127.0.0.1:4444/wd/hub", desired_capabilities: Selenium::WebDriver::Remote::Capabilities.send(:firefox, {}))
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=500, content-type="text/plain"
{"status":13,"value":{"message":"cannot create session firefox-52 on any hosts after 1 attempt(s)"}}
```


Hub is healthy:
<img width="573" alt="screen shot 2017-03-09 at 19 07 28" src="https://cloud.githubusercontent.com/assets/2598910/23761543/d05f0082-04fb-11e7-9339-2c564c4e299b.png">

When I create a remote session using its url directly, it launches firefox v52:
<img width="1280" alt="screen shot 2017-03-09 at 19 07 16" src="https://cloud.githubusercontent.com/assets/2598910/23761560/ddd8acea-04fb-11e7-88f4-1da9912f2284.png">

Probably it's beyond ggr responsibility, if so close issue.

Thanks,
Ivan

**Comment by vania-pooh** [comment]
```
cannot create session firefox-52 on any hosts after 1 attempt(s)
```
You should have on your hub a Firefox with version exactly equal to "52". Please check this. Don't see it on the screenshot.

**Comment by vania-pooh** [comment]
Btw, please use Selenium Grid and not Selenium RC.

**Comment by vania-pooh** [comment]
Btw, please use Selenium Grid and not Selenium RC.

**Comment by idanci** [comment]
What do you mean by
>  Firefox with version exactly equal to "52"

?

I have exactly one firefox installed in the system, 52.0. 
```bash
2017/03/09 22:10:29 [5] [SESSION_FAILED] [ivand] [10.0.2.2] [firefox-52.0] [localhost:4445]
 Error forwarding the new session cannot find : Capabilities [{acceptSslCerts=false, 
marionette=true, browserVersion=null, platformVersion=any, browserName=firefox, 
pageLoadStrategy=normal, takesScreenshot=false, takesElementScreenshot=false, 
platformName=null, version=52.0}]
```

There's also chrome which also throws `cannot create session chrome-56.0.2924.87` when trying to create a session
```bash
2017/03/09 22:20:09 [0] [SESSION_FAILED] [ivand] [10.0.2.2] [chrome-56.0.2924.87] 
[localhost:4445] Error forwarding the new session cannot find : Capabilities [{rotatable=false, 
nativeEvents=false, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@4481e8e3, 
browserName=chrome, takesScreenshot=false, javascriptEnabled=true, version=56.0.2924.87, 
cssSelectorsEnabled=true, platform=ANY}]
```

But that's another issue, want to move on with firefox first.

P.S. using selenium grid, launching with default options:
```bash
$ java -jar selenium-server-standalone-2.53.1.jar -port 4445 -role hub
$ java -jar selenium-server-standalone-2.53.1.jar -role node  -hub http://localhost:4445/grid/register
```

**Comment by vania-pooh** [comment]
You need to create a json file to node process (e.g. ```selenium-node.json```). Something like:
```
{
    "capabilities":
        [
            {
                "browserName": "firefox",
                "version": "42.0",
                "maxInstances": 1,
                "seleniumProtocol": "WebDriver",
                "platform": "LINUX"
            }
        ],
    "configuration":
        {
            "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
            "maxSession": 1,
            "register": true,
            "registerCycle": 5000
        }
}
```
Then pass this file to node like the following:
```
$ java -jar selenium-server-standalone-2.53.1.jar -role node -nodeConfig /path/to/selenium-node.json -hubHost localhost -hubPort 4445
```
Grid console should then look like:
![screen shot 2017-03-10 at 6 25 07 am](https://cloud.githubusercontent.com/assets/829320/23781006/c814a996-0563-11e7-9e25-f54bd3618cd8.png)
When setting up ggr you need to specify exactly ```42.0``` in quota XML file.

**Comment by aandryashin** [comment]
To simplify configuration, you can run only Selenium server instead of hub + node, but in that case you loose the ability to limit max instances.

**Comment by idanci** [comment]
@vania-pooh @aandryashin followed your instructions, works like a charm, you rock guys!
Going to try selenoid

**Comment by vania-pooh** [comment]
Glad to hear. Closing.
