### ISSUE TITLE
ggr with selenoid usage example

### ISSUE THREAD

**Issue by sskorol** [aandryashin/ggr#44]
Hi @vania-pooh @aandryashin,

I did followed both `ggr` and `selenoid` instructions, but can't run them together in docker containers. `Selenoid` works well, if I send commands directly to it. But I'm not able to route requests to `selenoid` via `ggr`.

First of all, the following command doesn't seem to open 4444 port on mac os x (el capitan).

```sh
docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host sskorol/ggr:latest
```
Container is started, but I'm not able to access it via localhost:4444.

Setting 4444, 4445 (`selenoid`) ports manually on container's startup fixed the problem, but browser's starting attempts via `http://skorol:password@localhost:4444/wd/hub` failed with the following logs in `ggr` container:

```sh
2017/03/26 14:21:50 [0] [SESSION_ATTEMPTED] [skorol] [172.17.0.1] [chrome-latest] [localhost:4445] [1]
2017/03/26 14:21:50 [0] [SESSION_FAILED] [skorol] [172.17.0.1] [chrome-latest] [localhost:4445] 
2017/03/26 14:21:50 [0] [SESSION_NOT_CREATED] [skorol] [172.17.0.1] [chrome-latest]
```
**skorol.xml**:
```xml
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
  <browser name="firefox" defaultVersion="latest">
      <version number="latest">
          <region name="1">
              <host name="localhost" port="4445" count="1"/>
          </region>
      </version>
  </browser>
  <browser name="chrome" defaultVersion="latest">
      <version number="latest">
          <region name="1">
              <host name="localhost" port="4445" count="1"/>
          </region>
      </version>
  </browser>
</qa:browsers>
```
**users.htpasswd**:
```sh
skorol:$apr1$gjjzc.Sp$bpxotCebvUKcYUS5f3Yrk1
```
Selenoid has been started with the following command:

```sh
docker run -d --name selenoid -p 4445:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:1.0.0
```
**browsers.json**
```json
{
  "firefox": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/firefox:latest",
        "port": "4445"
      }
    }
  },
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/chrome:latest",
        "port": "4445"
      }
    }
  }
}
```
Any help would be appreciated.

Thanks,
Sergey

**Comment by vania-pooh** [comment]
@sskorol this happens only when running Selenoid and Ggr on the same host. In that case when Ggr is being run in container and ```localhost``` is specified in its config it tries to connect to container's localhost and thus fails as there's no port 4445 listening **inside** Ggr container. In order to make this work you need to use Docker host machine IP address (something like ```172.17.0.1```) in Ggr XML files.
```xml
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
  <browser name="firefox" defaultVersion="latest">
      <version number="latest">
          <region name="1">
              <host name="172.17.0.1" port="4445" count="1"/>
          </region>
      </version>
  </browser>
  <browser name="chrome" defaultVersion="latest">
      <version number="latest">
          <region name="1">
              <host name="172.17.0.1" port="4445" count="1"/>
          </region>
      </version>
  </browser>
</qa:browsers>
```
Take a look at the following [question](http://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container) for more details on how to determine host machine IP.

**Comment by sskorol** [comment]
@vania-pooh thanks, will try. And what about `ggr` startup command? Seems like `--net host` doesn't really work on MacOS. Is there any valid alternative, or we need to specify ports manually?

Could you please also clarify how `ggr` talks to `selenoid` in terms of network communication? As both are using 4444 port in Dockerfile. So I'm a bit wondering which ports should be used / exposed while startup. Do we also need to link containers together if we run both locally?

**Comment by aandryashin** [comment]
Option ```--net host``` is not necessary. In practice ggr and selenoid run on different hosts, and do not need to customize port. When run locally you can easily remap ports, like the following:
```
ggr -p 4444:4444
selenoid1 -p 4445:4444
selenoid2 -p 4446:4444
...
```

**Comment by vania-pooh** [comment]
@sskorol ggr and selenoid are in fact smart proxies and use the same JSONWire protocol like Selenium does. In order to make them work you need to be sure that hosts and ports you specify in XML files are accessible to GGR. This can be achieved in different ways: ```--net host```, port forwarding via ```-p```, Docker links, etc. To check whether port and host is accessible you can use well-known tools like telnet, netcat and so on.

**Comment by sskorol** [comment]
@aandryashin @vania-pooh thanks, tried to test that, but was unexpectedly blocked with https://github.com/aandryashin/selenoid/issues/32

**Comment by sskorol** [comment]
@aandryashin @vania-pooh seems like manual port mapping + valid json / xml configuration did the trick. However, as I've mentioned in related issue, would be nice to add some clarifications to existing user guides to avoid confusion.

Thanks.

**Comment by vania-pooh** [comment]
@sskorol agreed.

**Comment by sskorol** [comment]
@vania-pooh @aandryashin btw, here's the script, which could be helpful for MacOS users in case of running selenoid with ggr within the same host:

```sh
#!/bin/bash
docker run -d --name selenoid -p 4445:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:latest
ip=`docker inspect --format {{.NetworkSettings.IPAddress}} selenoid`
xml ed --inplace -u '//host/@name' -v "$ip" /etc/grid-router/quota/username.xml
docker run -d --name ggr -p 4444:4444 -v /etc/grid-router/:/etc/grid-router:ro aandryashin/ggr
```
Where `xml` is a [XMLStarlet](http://xmlstar.sourceforge.net/overview.php) tool for xml manipulations.
