### ISSUE TITLE
Implement quota hot reload

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/ggr#9]
Should listen on filesystem events and reload XML files respectively.

**Comment by vania-pooh** [comment]
Also need to print all loaded XML files contents. In Java implementation it looks like the following:
```
2016-06-16 17:01:44,137 [1-thread-1] INFO  ConfigRepository     - Loaded quota configuration for [selenium] from [/etc/grid-router/quota/selenium.xml]:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:browsers xmlns:ns2="urn:config.gridrouter.qatools.ru">
...
```

**Comment by aandryashin** [comment]
Now configuration is printed. It is better to implement hot reloading when we add quota, in this case we can watch directory events instead of file events, it is more realible.

**Comment by vania-pooh** [comment]
@aandryashin please go ahead with directory-based implementation.

**Comment by aandryashin** [comment]
Done
